language: node_js
node_js:
  - 16
cache: npm

install:
  - npm install

script:
  - npm run test -- --coverage
  - npm run build

after_success:
  - CODECOV_TOKEN=$codecov_token npm run report-coverage



deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
