language: node_js
node_js:
  - npm audit fix --force
cache: npm

install:
  - npm audit fix --force
  - npm install

script:
  - npm run test -- --coverage
  - npm run build

after_success:
  - CODECOV_TOKEN=$codecov_token npm run report-coverage
  
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
